// <auto-generated />
using System;
using Examen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examen.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Examen.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Costo")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.Property<string>("RequisitosPrevios")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Servicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Costo = 100,
                            Descripcion = "holaaaaaaaa",
                            Nombre = "Aldair",
                            RequisitosPrevios = "ejemplo1"
                        },
                        new
                        {
                            Id = 2,
                            Costo = 200,
                            Descripcion = "holaaaaaaaa",
                            Nombre = "Fer",
                            RequisitosPrevios = "ejemplo2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
